name: "Project Mirroring Action"
description: "GitHub action to mirror the project cards between two GitHub projects"
inputs:
  trigger:
    description: "The action trigger"
    default: ${{ github.event_name }}
    required: true
  parent_token:
    description: "GITHUB_TOKEN or a repo scoped PAT"
    default: ${{ secrets.GITHUB_TOKEN }}
    required: true
  parent_repository:
    description: "The parent repo"
    default: ${{ github.repository }}
    required: true
  parent_project_number:
    description: "Number of the project to be mirrored"
    required: true
  issue_number:
    description: "The ID of the issue on the parent board triggering an update to child"
    default: ${{ github.event.issue.number }}
    required: true
  mirror_tag_name:
    description: "Tag name in parent project to track children to tag"
    required: true
  child_token:
    description: "Repo scoped PAT"
    required: true
  child_repository:
    description: "The child repo"
    required: true
  child_project_number:
    description: "Number of the project mirroring"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
